# 服务器配置
server:
  port: 8085
  servlet:
    context-path: /immuse-risk
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 10

spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/medical?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  
  # Jackson配置
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false

  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  # 静态资源配置
  web:
    resources:
      static-locations: classpath:static/,file:${file.upload-dir}
  mvc:
    static-path-pattern: /**
  
  # 邮件配置
  mail:
    host: smtp.qq.com
    username: 2637201516@qq.com
    password: uwsfqtpwiftsbjgb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
    port: 465
    default-encoding: UTF-8
    nickname: 自身免疫病风险预测平台

# 自定义配置：图片路径前缀（用于Service层转换路径）
image:
  base-path: http://localhost:8085/immuse-risk/static/
# 文件上传路径配置
file:
  upload-dir: ./upload/

# MyBatis配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.immuse_risk.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Shiro配置
shiro:
  web:
    enabled: true
  loginUrl: /login
  successUrl: /index
  unauthorizedUrl: /unauthorized
  sessionManager:
    sessionIdCookieEnabled: true
    sessionIdUrlRewritingEnabled: false
